server:
  port: 8080

spring:
  profiles:
    active: local
  data:
    mongodb:
      port: 27017
      database: users
      username: mongo
      password: mongo_password
      authentication-database: admin